### PR TITLE
[GameController] Implementing game controller

### PR DESCRIPTION
**Pull request by pranathip**

### CODE REVIEW

**Comment by pranathip** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/5" target="_blank">Graphite</a> 
    * **PR #6** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/6" target="_blank">Graphite</a> 
      * **PR #7** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7" target="_blank">Graphite</a>  👈
        * **PR #8** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/8" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7?utm_source=stack-comment).

**Comment by pranathip** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/5" target="_blank">Graphite</a> 
    * **PR #6** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/6" target="_blank">Graphite</a> 
      * **PR #7** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7" target="_blank">Graphite</a>  👈
        * **PR #8** <a href="https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/8" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7?utm_source=stack-comment).

**Review by pranasaurus-rex — APPROVED** [review]
great changes!

**Comment by pranathip** [comment]
@pranathip started a stack merge that includes this pull request via [Graphite](https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7).

**Comment by pranathip** [comment]
@pranathip merged this pull request with [Graphite](https://app.stg.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/7).

**Pull request merged**
