### PR TITLE
[Styling] Adding styling to the 2048 app

### PR DESCRIPTION
**Pull request by pranathip**
# Summary
Adding some basic styling to the app!

# Images/videos

### CODE REVIEW

**Comment by pranathip** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12** <a href="https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/12" target="_blank">Graphite</a> 
    * **PR #13** <a href="https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/13" target="_blank">Graphite</a> 
      * **PR #14** <a href="https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/14" target="_blank">Graphite</a> 
        * **PR #15** <a href="https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/15" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/15?utm_source=stack-comment).

**Review by pranasaurus-rex — APPROVED** [review]
Added via Giphy

**Comment by pranathip** [comment]
@pranathip started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/15).

**Comment by pranathip** [comment]
@pranathip merged this pull request with [Graphite](https://app.graphite.dev/github/pr/pranathip/pranathi-2048-react-app/15).

**Pull request merged**
